CREATE PROCEDURE findTable()
BEGIN
	SELECT infSch.TABLE_NAME AS tab_name, infSch.COLUMN_NAME AS col_name, infSch.DATA_TYPE AS data_type
	FROM INFORMATION_SCHEMA.COLUMNS infSch
	WHERE TABLE_NAME LIKE 'e%s' AND TABLE_SCHEMA='ri_db'
	ORDER BY infSch.TABLE_NAME, infSch.COLUMN_NAME;
END